version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0

  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore FoodDeliveryApplication/FoodDeliveryApplication.csproj

  build:
    commands:
      - echo Build started on `date`
      - dotnet build FoodDeliveryApplication/FoodDeliveryApplication.csproj

  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release -r linux-x64 -o ./FoodDeliveryApplication/FoodDeliveryApplication.csproj

artifacts:
  files:
    - '**/*'
